[package]
name = "error-rules"
version = "0.1.2"
authors = ["Andrey Dyldin <and@cesbo.com>"]
description = "Chained error handling"
documentation = "https://docs.rs/error-rules"
repository = "https://github.com/cesbo/error-rules"
edition = "2018"
keywords = ["error"]
license = "MIT"

[dependencies]
