[package]
name = "error-derive"
version = "0.2.0"
authors = ["Andrey Dyldin <and@cesbo.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "0.6"
syn = "0.15"
proc-macro2 = "0.4"

[dev-dependencies.error-rules]
version = "0.2"
path = ".."
